<template>
  <page-column>
    <page-header></page-header>
    <page-row>
      <page-aside></page-aside>
      <page-main></page-main>
    </page-row>
    <page-footer></page-footer>
  </page-column>
</template>
